"""add thumbnail filename

Revision ID: 539992c7e971
Revises: 8fb454c86939
Create Date: 2026-08-06 22:26:31.721565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539992c7e971'
down_revision = '8fb454c86939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_filename')

    # ### end Alembic commands ###
